import Head from 'next/head'
import { Flex, Text, Heading, Input, Button, Center } from '@chakra-ui/react'
import styles from '@/styles/Home.module.css'

import { Header } from '../components/Header/Header'
import { HomePage } from '../components/Home/Home'
import { Footer } from '../components/Footer/Footer'


export default function Home() {
  return (
    <>

      <Head>
        <title>Snyker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <HomePage/>
      <Footer/>
    </>

// Design de la page home

  )
}
